modify check script to run all tests

diff --git a/strgery/check b/strgery/check
--- a/strgery/check
+++ b/strgery/check
@@ -6,30 +6,26 @@
 # local testing. You may need to modify the exact run commands to work on your
 # system.
 
-if [[ "$1" == *py ]] # Python 3
-then
-  output=$(python3 "$1" < "$2.in" | diff -Z "$2.ans" -)
-  found=true
-elif [[ "$1" == *java ]] # Java
-then
-  javac "$1" -d ./bin
-  output=$(java -cp ./bin "$1" < "$2.in" | diff -Z "$2.ans" -)
-  rm -rf ./bin
-  found=true
-else
-  echo "Unrecognized solution format: $1";
-fi
+# passed=1
 
-# If the diff output is empty, then it matches perfectly, so it passes.
-# Otherwise, it fails.
-
-if [[ $found == "true" ]]
-then
-  if [[ $output == "" ]]
+for i in data/secret/*.in; do
+  test_path="${i%.*}"
+  test_name=$(basename -- "$test_path")
+  result=0
+  echo "Running $test_path"
+  if [[ "$1" == *.py ]] # Python 3
   then
-    echo "Passed!"
+    python3 "$1" < "$test_path.in" > "out/$test_name.out"
+    if ! diff -Zq "$test_path.ans" "out/$test_name.out" > /dev/null; then
+      echo "failed on test $test_path"
+      diff -Z "$test_path.ans" "out/$test_name.out"
+    fi
+  # elif [[ "$1" == *java ]] # Java
+  # then
+  #   javac "$1" -d ./bin
+  #   output=$(java -cp ./bin "$1" < "$2.in" | diff -Z "$2.ans" -)
+  #   rm -rf ./bin
   else
-    echo "$output"
-    echo "Failed!"
+    echo "Unrecognized solution format: $1";
   fi
-fi
+done
