even better check script

diff --git a/strgery/check b/strgery/check
--- a/strgery/check
+++ b/strgery/check
@@ -20,16 +20,14 @@ for i in data/secret/secret_*$test_set*.in; do
   if [[ "$1" == *.py ]] # Python 3
   then
     python3 "$1" < "$test_path.in" > "out/$test_name.out"
-    if ! ./executables/compare/compare.py "$test_path.in" "$test_path.ans" < "out/$test_name.out"; then
-      echo "failed on test $test_path"
-      diff -Z "$test_path.ans" "out/$test_name.out"
-    fi
-  # elif [[ "$1" == *java ]] # Java
-  # then
-  #   javac "$1" -d ./bin
-  #   output=$(java -cp ./bin "$1" < "$2.in" | diff -Z "$2.ans" -)
-  #   rm -rf ./bin
+  elif [[ -x "$1" ]] # cpp
+  then
+    ./"$1" < "$test_path.in" > "out/$test_name.out"
   else
     echo "Unrecognized solution format: $1";
+  fi
+  if ! ./executables/compare/compare.py "$test_path.in" "$test_path.ans" < "out/$test_name.out"; then
+    echo "failed on test $test_path"
+    diff -Z "$test_path.ans" "out/$test_name.out"
   fi
 done
